### ISSUE TITLE
This is a problem

### ISSUE THREAD

**Issue by hzm401** [Mahedi-61/MIU_Fall_2019#22]
hasan@hasan-HP-ProBook-450-G3:~$ /bin/python3.8 /home/hasan/Desktop/Project/config.py
  File "/home/hasan/Desktop/Project/config.py", line 25
    return os.path.join(root_path(),'dataset') 
    ^
IndentationError: expected an indented block
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
  File "/home/hasan/Desktop/Project/config.py", line 25
    return os.path.join(root_path(),'dataset') 
    ^
IndentationError: expected an indented block
hasan@hasan-HP-ProBook-450-G3:~$ ### ### ****

**Comment by mzminhaz5683** [comment]
May be you miss the indentation before return... Check it out... I give the function's code..
![Screenshot from 2019-11-28 20-54-17](https://user-images.githubusercontent.com/52498840/69815831-59522d80-1221-11ea-9a4e-ab1d4d87d4dd.png)
